### ISSUE TITLE
What does REDI2 do?

### ISSUE THREAD

**Issue by pbchase** [ctsit/redi2#18]
The README doesn't say what redi2 does. I think the README need to open with a few sentences summarizing what REDI does. Maybe something like this:

> REDI2 is a suite of tools designed to transform the CSV data and load it into the fields and events of a REDCap project. REDI2 excels at transforming large, longitudinal data sets and loading them into REDCap in a scripted, repeatable fashion. REDI2 is fast and has minimal effects on REDCap server load.

Is that too short.  Is there more awesome to share?

**Comment by DevMattM** [comment]
I like it, thanks. We'll update the README
